### ISSUE TITLE
link takes me to a 404 error! :O

### ISSUE THREAD

**Issue by IcingHackz** [JBYT27/BHTML-Compiler#3]
@JBYT27 So...I've been ~~stalking~~ looking at this project. And for all the links you provided it returns a `404` error. That's because you moved all of the readme's to a file called `README's`.

What you want to do is for every link add a `README's/` in front of the file name in the link. For example for the details.md instead of  `https://github.com/JBYT27/BHTML-Compiler/blob/master/Details.md`, make it `https://github.com/JBYT27/BHTML-Compiler/blob/master/README's/Details.md`. That should fix it.

###### and if you were about to do what i just said sry for being a bother D:

**Comment by JBYT27** [comment]
aha, ok! Thanks!
